"""add:username

Revision ID: df2b716d477c
Revises: 450e705da2b4
Create Date: 2024-11-05 09:01:46.191137

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df2b716d477c'
down_revision = '450e705da2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=155), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('date_done', sa.DateTime(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=155), nullable=True),
    sa.Column('args', sa.LargeBinary(), nullable=True),
    sa.Column('kwargs', sa.LargeBinary(), nullable=True),
    sa.Column('worker', sa.String(length=155), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('queue', sa.String(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_taskmeta_pkey')),
    sa.UniqueConstraint('task_id', name=op.f('celery_taskmeta_task_id_key'))
    )
    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taskset_id', sa.String(length=155), nullable=True),
    sa.Column('result', sa.PickleType(), nullable=True),
    sa.Column('date_done', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_tasksetmeta_pkey')),
    sa.UniqueConstraint('taskset_id', name=op.f('celery_tasksetmeta_taskset_id_key'))
    )
    op.create_table('tool_providers',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=40), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tool_provider_pkey'),
    sa.UniqueConstraint('tenant_id', 'tool_name', name='unique_tool_provider_tool_name')
    )
    op.drop_table('embedding_vector_index_e16132be_d698_4c92_bb19_17bc49400a23_nod')
    op.drop_table('embedding_vector_index_b961ddf5_4f60_49ff_a827_76e22fb5f97e_nod')
    op.drop_table('embedding_vector_index_44b8bc1c_df5a_47cf_82d3_376addd9db79_nod')
    op.drop_table('embedding_vector_index_882713d3_5ded_4547_939a_4233f1af81ae_nod')
    op.drop_table('embedding_vector_index_e3d705a5_5cd6_4698_aaa4_585bfcb36460_nod')
    op.drop_table('embedding_vector_index_c24419f0_38cf_45ca_ac5e_81c3c2e787a8_nod')
    op.drop_table('embedding_vector_index_1e3e13c3_2ad7_450b_a7cb_f3ef7efdc569_nod')
    op.drop_table('embedding_vector_index_69950a0f_ffb6_4641_bacf_779929f93f9f_nod')
    op.drop_table('embedding_vector_index_d3e0183e_a108_4599_a7ab_b90e2b7acb95_nod')
    op.drop_table('embedding_vector_index_e4c6a2f6_9403_4ea2_a272_59256809fd72_nod')
    op.drop_table('embedding_vector_index_7ac532be_f746_4635_a438_82c5d0fe3daa_nod')
    op.drop_table('embedding_vector_index_3f52b98b_ca31_4000_b796_5ac682bad5da_nod')
    op.drop_table('embedding_vector_index_e71b2ec6_c516_488e_b665_b1c57ef97c5e_nod')
    op.drop_table('embedding_vector_index_12ff3df9_0e1d_4c87_a37d_5bd2dd63c260_nod')
    op.drop_table('embedding_vector_index_e6ae390c_8daf_43fb_9958_3be5bee640d3_nod')
    op.drop_table('embedding_vector_index_d185d041_439e_4d65_b85c_e90c8ae926fd_nod')
    op.drop_table('embedding_vector_index_31fdeac1_9005_4a2f_9237_e70f4ab65abe_nod')
    op.drop_table('embedding_vector_index_f447ed75_3787_499a_9f68_6e42d775acfb_nod')
    op.drop_table('embedding_vector_index_76070006_5206_4e81_876f_151f5d616b3a_nod')
    op.drop_table('embedding_vector_index_ac9e4e5e_5976_412d_91bc_72a12c8316be_nod')
    op.drop_table('embedding_vector_index_b4ece3bf_5a68_4644_9fea_f2cbf80c7257_nod')
    op.drop_table('embedding_vector_index_2a84507e_b0bc_4b33_b578_7d06d2317d9d_nod')
    op.drop_table('embedding_vector_index_1df66eb2_37ef_419e_b96e_b9bceea9ad9f_nod')
    op.drop_table('embedding_vector_index_5da9b999_a65f_42d4_8bce_6c368e3c53e0_nod')
    op.drop_table('embedding_vector_index_15aa5c3e_80cd_4882_8aff_3140e36b5bda_nod')
    op.drop_table('embedding_vector_index_59875b51_d156_40a7_bfc6_ede19885812c_nod')
    op.drop_table('embedding_vector_index_b445bd6e_03c6_443d_905a_ccb541b5e726_nod')
    op.drop_table('embedding_vector_index_53f123dd_a8a6_425e_8ffc_f0a20267df81_nod')
    op.drop_table('embedding_vector_index_d411330f_21df_482c_ad26_9691660bcb3a_nod')
    op.drop_table('embedding_vector_index_d88b22ea_eb08_4f78_b25f_29cdcd8d1768_nod')
    op.drop_table('embedding_vector_index_b33681f8_aa23_4e29_a43f_1b0c86d87980_nod')
    op.drop_table('embedding_vector_index_5137337e_722a_48f4_8ceb_4f51f1e1c7e2_nod')
    op.drop_table('embedding_vector_index_0fe39b77_76e9_4257_9454_15c72988b4ba_nod')
    op.drop_table('embedding_vector_index_ea1eea8b_29d3_415a_a60b_b2f1c0c239d7_nod')
    op.drop_table('embedding_vector_index_8a6409ef_0841_4f01_9e29_8dc6c5af8aed_nod')
    op.drop_table('embedding_vector_index_29c53623_2c53_4981_987c_48d9ad4dfa69_nod')
    op.drop_table('embedding_vector_index_729c6e9b_9ad3_4a70_9809_522980b5545e_nod')
    op.drop_table('embedding_vector_index_2fa3d87c_5b4e_4247_a9e3_c645f7665109_nod')
    op.drop_table('embedding_vector_index_91a350f5_f2bb_4c2d_92ef_15a3ab92cbf0_nod')
    op.drop_table('embedding_vector_index_1cdf1643_7faf_4d2e_9a6f_f920eaa492af_nod')
    op.drop_table('embedding_vector_index_02471a62_7ab1_4e6f_bf71_28c435c704d9_nod')
    op.drop_table('embedding_vector_index_05bd43b9_6635_47cf_a1a3_ec226432ede9_nod')
    op.drop_table('embedding_vector_index_774b9727_7e94_4944_808a_e8269bcf7853_nod')
    op.drop_table('embedding_vector_index_cceb0c23_e35a_4169_a76f_10d5344eb25f_nod')
    op.drop_table('embedding_vector_index_014edcb8_1f3c_4c57_93bc_0bea2ba3cc26_nod')
    op.drop_table('embedding_vector_index_8ea3c6e5_449f_4ede_ae68_53c46c482cb8_nod')
    op.drop_table('embedding_vector_index_742ab212_404d_4a37_8a80_2f1087db9024_nod')
    op.drop_table('embedding_vector_index_2b38b28e_53e1_41b1_b997_d0528f96aad0_nod')
    op.drop_table('embedding_vector_index_62d371d3_5f39_4fc1_a863_4bab6b8d64d1_nod')
    op.drop_table('embedding_vector_index_82cf7eaf_252f_4e7f_8d63_d1e9a3270a8d_nod')
    op.drop_table('embedding_vector_index_089c273d_ab75_4ea2_aec3_7f193b27915f_nod')
    op.drop_table('embedding_vector_index_228381b1_85f6_46cf_8bba_dbc34fbf282a_nod')
    op.drop_table('embedding_vector_index_36ba8de7_7b15_4a43_94ba_f91948959e2d_nod')
    op.drop_table('embedding_vector_index_5830c594_3cb0_483d_baf8_d8c8c2f87eda_nod')
    op.drop_table('embedding_vector_index_7cbbfe2e_560c_4fb4_9e55_240ea3172f08_nod')
    op.drop_table('embedding_vector_index_a9aebcdf_fc9c_4a55_822e_bedb5084275b_nod')
    op.drop_table('embedding_vector_index_14ab0970_8ec3_4636_aea9_2ad2571dfbd4_nod')
    op.drop_table('embedding_vector_index_bf357f39_6657_4335_b4a8_08981585a505_nod')
    op.drop_table('embedding_vector_index_5bef0957_3ca6_4e79_88fe_c324eb004f74_nod')
    op.drop_table('embedding_vector_index_a91eb511_a30a_4484_b372_32a2ba806f4c_nod')
    op.drop_table('embedding_vector_index_3d7fef32_68c0_4b76_907d_fd0f3857811c_nod')
    op.drop_table('embedding_vector_index_1c5ec143_bcc8_4caa_a5c9_970a3de5c9e7_nod')
    op.drop_table('embedding_vector_index_f75b112d_e6a3_41e1_90f7_8443c9814f4b_nod')
    op.drop_table('embedding_vector_index_a4a6f4d3_95cf_44ed_b36f_c24841c34823_nod')
    op.drop_table('embedding_vector_index_3a29c217_12e2_4c7e_acde_b0f0e52aedbf_nod')
    op.drop_table('embedding_vector_index_5be40b38_1e90_4903_9af1_d2ee6cb04146_nod')
    op.drop_table('embedding_vector_index_8cc97c1a_dc60_450c_9058_f186170113be_nod')
    op.drop_table('embedding_vector_index_b0ed67d9_b5a8_4199_bb69_74f8b01a5dc8_nod')
    op.drop_table('embedding_vector_index_7a630046_5152_4c72_8fda_df3cfa802dc2_nod')
    op.drop_table('embedding_vector_index_e1b71cfe_3309_486b_86c6_5151a6f52971_nod')
    op.drop_table('embedding_vector_index_0f8ab682_d6dd_4113_a37f_2097c0e4a354_nod')
    op.drop_table('embedding_vector_index_d696482e_5d41_4b0b_b06e_fba861c03699_nod')
    op.drop_table('embedding_vector_index_9c1dd623_3243_43b8_857d_2c42ad69a077_nod')
    op.drop_table('embedding_vector_index_c8599f41_b54e_438b_95a6_357e00b76d7d_nod')
    op.drop_table('embedding_vector_index_be47ec94_d5d4_497f_8b56_5460ea9d1d7e_nod')
    op.drop_table('embedding_vector_index_33f6eeb5_586b_453d_bc6f_44c5e21b9ba6_nod')
    op.drop_table('embedding_vector_index_8e238b14_16ff_4db6_b222_4877ccab8ab4_nod')
    op.drop_table('embedding_vector_index_8b3107ad_a52a_48da_9449_af8691f4abbc_nod')
    op.drop_table('embedding_vector_index_493406e3_a92c_454b_9e8f_30473217b23d_nod')
    op.drop_table('embedding_vector_index_73e708e0_cc26_442d_822b_e57932f3e662_nod')
    op.drop_table('embedding_vector_index_fe4c0f05_2c88_4e46_8a29_2807c2af82c6_nod')
    op.drop_table('embedding_vector_index_0ff387ef_a7ba_4284_aad9_e9bb0e019a4c_nod')
    op.drop_table('embedding_vector_index_e742ebbf_d1d6_471f_9e15_ff7e91ff8cc4_nod')
    op.drop_table('embedding_vector_index_ba2fcd34_9500_43ad_a515_a73cc875b399_nod')
    op.drop_table('embedding_vector_index_d3613753_174e_4dbd_b7aa_01e087161886_nod')
    op.drop_table('embedding_vector_index_cb789dc0_27ee_4bf9_a9ae_96fb9c214bca_nod')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index('workflow__conversation_variables_app_id_idx')
        batch_op.drop_index('workflow__conversation_variables_created_at_idx')
        batch_op.create_index(batch_op.f('workflow_conversation_variables_app_id_idx'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('workflow_conversation_variables_created_at_idx'), ['created_at'], unique=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('graph',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('features',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('features',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('graph',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('workflow_conversation_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('workflow_conversation_variables_created_at_idx'))
        batch_op.drop_index(batch_op.f('workflow_conversation_variables_app_id_idx'))
        batch_op.create_index('workflow__conversation_variables_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('workflow__conversation_variables_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('inputs',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('username')

    op.create_table('embedding_vector_index_cb789dc0_27ee_4bf9_a9ae_96fb9c214bca_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_cb789dc0_27ee_4bf9_a9ae_96fb9c214bc_pkey')
    )
    op.create_table('embedding_vector_index_d3613753_174e_4dbd_b7aa_01e087161886_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_d3613753_174e_4dbd_b7aa_01e08716188_pkey')
    )
    op.create_table('embedding_vector_index_ba2fcd34_9500_43ad_a515_a73cc875b399_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_ba2fcd34_9500_43ad_a515_a73cc875b39_pkey')
    )
    op.create_table('embedding_vector_index_e742ebbf_d1d6_471f_9e15_ff7e91ff8cc4_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_e742ebbf_d1d6_471f_9e15_ff7e91ff8cc_pkey')
    )
    op.create_table('embedding_vector_index_0ff387ef_a7ba_4284_aad9_e9bb0e019a4c_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_0ff387ef_a7ba_4284_aad9_e9bb0e019a4_pkey')
    )
    op.create_table('embedding_vector_index_fe4c0f05_2c88_4e46_8a29_2807c2af82c6_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_fe4c0f05_2c88_4e46_8a29_2807c2af82c_pkey')
    )
    op.create_table('embedding_vector_index_73e708e0_cc26_442d_822b_e57932f3e662_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_73e708e0_cc26_442d_822b_e57932f3e66_pkey')
    )
    op.create_table('embedding_vector_index_493406e3_a92c_454b_9e8f_30473217b23d_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_493406e3_a92c_454b_9e8f_30473217b23_pkey')
    )
    op.create_table('embedding_vector_index_8b3107ad_a52a_48da_9449_af8691f4abbc_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_8b3107ad_a52a_48da_9449_af8691f4abb_pkey')
    )
    op.create_table('embedding_vector_index_8e238b14_16ff_4db6_b222_4877ccab8ab4_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_8e238b14_16ff_4db6_b222_4877ccab8ab_pkey')
    )
    op.create_table('embedding_vector_index_33f6eeb5_586b_453d_bc6f_44c5e21b9ba6_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_33f6eeb5_586b_453d_bc6f_44c5e21b9ba_pkey')
    )
    op.create_table('embedding_vector_index_be47ec94_d5d4_497f_8b56_5460ea9d1d7e_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_be47ec94_d5d4_497f_8b56_5460ea9d1d7_pkey')
    )
    op.create_table('embedding_vector_index_c8599f41_b54e_438b_95a6_357e00b76d7d_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_c8599f41_b54e_438b_95a6_357e00b76d7_pkey')
    )
    op.create_table('embedding_vector_index_9c1dd623_3243_43b8_857d_2c42ad69a077_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_9c1dd623_3243_43b8_857d_2c42ad69a07_pkey')
    )
    op.create_table('embedding_vector_index_d696482e_5d41_4b0b_b06e_fba861c03699_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_d696482e_5d41_4b0b_b06e_fba861c0369_pkey')
    )
    op.create_table('embedding_vector_index_0f8ab682_d6dd_4113_a37f_2097c0e4a354_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_0f8ab682_d6dd_4113_a37f_2097c0e4a35_pkey')
    )
    op.create_table('embedding_vector_index_e1b71cfe_3309_486b_86c6_5151a6f52971_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_e1b71cfe_3309_486b_86c6_5151a6f5297_pkey')
    )
    op.create_table('embedding_vector_index_7a630046_5152_4c72_8fda_df3cfa802dc2_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_7a630046_5152_4c72_8fda_df3cfa802dc_pkey')
    )
    op.create_table('embedding_vector_index_b0ed67d9_b5a8_4199_bb69_74f8b01a5dc8_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_b0ed67d9_b5a8_4199_bb69_74f8b01a5dc_pkey')
    )
    op.create_table('embedding_vector_index_8cc97c1a_dc60_450c_9058_f186170113be_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_8cc97c1a_dc60_450c_9058_f186170113b_pkey')
    )
    op.create_table('embedding_vector_index_5be40b38_1e90_4903_9af1_d2ee6cb04146_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_5be40b38_1e90_4903_9af1_d2ee6cb0414_pkey')
    )
    op.create_table('embedding_vector_index_3a29c217_12e2_4c7e_acde_b0f0e52aedbf_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_3a29c217_12e2_4c7e_acde_b0f0e52aedb_pkey')
    )
    op.create_table('embedding_vector_index_a4a6f4d3_95cf_44ed_b36f_c24841c34823_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_a4a6f4d3_95cf_44ed_b36f_c24841c3482_pkey')
    )
    op.create_table('embedding_vector_index_f75b112d_e6a3_41e1_90f7_8443c9814f4b_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_f75b112d_e6a3_41e1_90f7_8443c9814f4_pkey')
    )
    op.create_table('embedding_vector_index_1c5ec143_bcc8_4caa_a5c9_970a3de5c9e7_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_1c5ec143_bcc8_4caa_a5c9_970a3de5c9e_pkey')
    )
    op.create_table('embedding_vector_index_3d7fef32_68c0_4b76_907d_fd0f3857811c_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_3d7fef32_68c0_4b76_907d_fd0f3857811_pkey')
    )
    op.create_table('embedding_vector_index_a91eb511_a30a_4484_b372_32a2ba806f4c_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_a91eb511_a30a_4484_b372_32a2ba806f4_pkey')
    )
    op.create_table('embedding_vector_index_5bef0957_3ca6_4e79_88fe_c324eb004f74_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_5bef0957_3ca6_4e79_88fe_c324eb004f7_pkey')
    )
    op.create_table('embedding_vector_index_bf357f39_6657_4335_b4a8_08981585a505_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_bf357f39_6657_4335_b4a8_08981585a50_pkey')
    )
    op.create_table('embedding_vector_index_14ab0970_8ec3_4636_aea9_2ad2571dfbd4_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_14ab0970_8ec3_4636_aea9_2ad2571dfbd_pkey')
    )
    op.create_table('embedding_vector_index_a9aebcdf_fc9c_4a55_822e_bedb5084275b_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_a9aebcdf_fc9c_4a55_822e_bedb5084275_pkey')
    )
    op.create_table('embedding_vector_index_7cbbfe2e_560c_4fb4_9e55_240ea3172f08_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_7cbbfe2e_560c_4fb4_9e55_240ea3172f0_pkey')
    )
    op.create_table('embedding_vector_index_5830c594_3cb0_483d_baf8_d8c8c2f87eda_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_5830c594_3cb0_483d_baf8_d8c8c2f87ed_pkey')
    )
    op.create_table('embedding_vector_index_36ba8de7_7b15_4a43_94ba_f91948959e2d_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_36ba8de7_7b15_4a43_94ba_f91948959e2_pkey')
    )
    op.create_table('embedding_vector_index_228381b1_85f6_46cf_8bba_dbc34fbf282a_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_228381b1_85f6_46cf_8bba_dbc34fbf282_pkey')
    )
    op.create_table('embedding_vector_index_089c273d_ab75_4ea2_aec3_7f193b27915f_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_089c273d_ab75_4ea2_aec3_7f193b27915_pkey')
    )
    op.create_table('embedding_vector_index_82cf7eaf_252f_4e7f_8d63_d1e9a3270a8d_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_82cf7eaf_252f_4e7f_8d63_d1e9a3270a8_pkey')
    )
    op.create_table('embedding_vector_index_62d371d3_5f39_4fc1_a863_4bab6b8d64d1_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_62d371d3_5f39_4fc1_a863_4bab6b8d64d_pkey')
    )
    op.create_table('embedding_vector_index_2b38b28e_53e1_41b1_b997_d0528f96aad0_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_2b38b28e_53e1_41b1_b997_d0528f96aad_pkey')
    )
    op.create_table('embedding_vector_index_742ab212_404d_4a37_8a80_2f1087db9024_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_742ab212_404d_4a37_8a80_2f1087db902_pkey')
    )
    op.create_table('embedding_vector_index_8ea3c6e5_449f_4ede_ae68_53c46c482cb8_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_8ea3c6e5_449f_4ede_ae68_53c46c482cb_pkey')
    )
    op.create_table('embedding_vector_index_014edcb8_1f3c_4c57_93bc_0bea2ba3cc26_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_014edcb8_1f3c_4c57_93bc_0bea2ba3cc2_pkey')
    )
    op.create_table('embedding_vector_index_cceb0c23_e35a_4169_a76f_10d5344eb25f_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_cceb0c23_e35a_4169_a76f_10d5344eb25_pkey')
    )
    op.create_table('embedding_vector_index_774b9727_7e94_4944_808a_e8269bcf7853_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_774b9727_7e94_4944_808a_e8269bcf785_pkey')
    )
    op.create_table('embedding_vector_index_05bd43b9_6635_47cf_a1a3_ec226432ede9_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_05bd43b9_6635_47cf_a1a3_ec226432ede_pkey')
    )
    op.create_table('embedding_vector_index_02471a62_7ab1_4e6f_bf71_28c435c704d9_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_02471a62_7ab1_4e6f_bf71_28c435c704d_pkey')
    )
    op.create_table('embedding_vector_index_1cdf1643_7faf_4d2e_9a6f_f920eaa492af_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_1cdf1643_7faf_4d2e_9a6f_f920eaa492a_pkey')
    )
    op.create_table('embedding_vector_index_91a350f5_f2bb_4c2d_92ef_15a3ab92cbf0_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_91a350f5_f2bb_4c2d_92ef_15a3ab92cbf_pkey')
    )
    op.create_table('embedding_vector_index_2fa3d87c_5b4e_4247_a9e3_c645f7665109_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_2fa3d87c_5b4e_4247_a9e3_c645f766510_pkey')
    )
    op.create_table('embedding_vector_index_729c6e9b_9ad3_4a70_9809_522980b5545e_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_729c6e9b_9ad3_4a70_9809_522980b5545_pkey')
    )
    op.create_table('embedding_vector_index_29c53623_2c53_4981_987c_48d9ad4dfa69_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_29c53623_2c53_4981_987c_48d9ad4dfa6_pkey')
    )
    op.create_table('embedding_vector_index_8a6409ef_0841_4f01_9e29_8dc6c5af8aed_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_8a6409ef_0841_4f01_9e29_8dc6c5af8ae_pkey')
    )
    op.create_table('embedding_vector_index_ea1eea8b_29d3_415a_a60b_b2f1c0c239d7_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_ea1eea8b_29d3_415a_a60b_b2f1c0c239d_pkey')
    )
    op.create_table('embedding_vector_index_0fe39b77_76e9_4257_9454_15c72988b4ba_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_0fe39b77_76e9_4257_9454_15c72988b4b_pkey')
    )
    op.create_table('embedding_vector_index_5137337e_722a_48f4_8ceb_4f51f1e1c7e2_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_5137337e_722a_48f4_8ceb_4f51f1e1c7e_pkey')
    )
    op.create_table('embedding_vector_index_b33681f8_aa23_4e29_a43f_1b0c86d87980_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_b33681f8_aa23_4e29_a43f_1b0c86d8798_pkey')
    )
    op.create_table('embedding_vector_index_d88b22ea_eb08_4f78_b25f_29cdcd8d1768_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_d88b22ea_eb08_4f78_b25f_29cdcd8d176_pkey')
    )
    op.create_table('embedding_vector_index_d411330f_21df_482c_ad26_9691660bcb3a_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_d411330f_21df_482c_ad26_9691660bcb3_pkey')
    )
    op.create_table('embedding_vector_index_53f123dd_a8a6_425e_8ffc_f0a20267df81_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_53f123dd_a8a6_425e_8ffc_f0a20267df8_pkey')
    )
    op.create_table('embedding_vector_index_b445bd6e_03c6_443d_905a_ccb541b5e726_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_b445bd6e_03c6_443d_905a_ccb541b5e72_pkey')
    )
    op.create_table('embedding_vector_index_59875b51_d156_40a7_bfc6_ede19885812c_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_59875b51_d156_40a7_bfc6_ede19885812_pkey')
    )
    op.create_table('embedding_vector_index_15aa5c3e_80cd_4882_8aff_3140e36b5bda_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_15aa5c3e_80cd_4882_8aff_3140e36b5bd_pkey')
    )
    op.create_table('embedding_vector_index_5da9b999_a65f_42d4_8bce_6c368e3c53e0_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_5da9b999_a65f_42d4_8bce_6c368e3c53e_pkey')
    )
    op.create_table('embedding_vector_index_1df66eb2_37ef_419e_b96e_b9bceea9ad9f_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_1df66eb2_37ef_419e_b96e_b9bceea9ad9_pkey')
    )
    op.create_table('embedding_vector_index_2a84507e_b0bc_4b33_b578_7d06d2317d9d_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_2a84507e_b0bc_4b33_b578_7d06d2317d9_pkey')
    )
    op.create_table('embedding_vector_index_b4ece3bf_5a68_4644_9fea_f2cbf80c7257_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_b4ece3bf_5a68_4644_9fea_f2cbf80c725_pkey')
    )
    op.create_table('embedding_vector_index_ac9e4e5e_5976_412d_91bc_72a12c8316be_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_ac9e4e5e_5976_412d_91bc_72a12c8316b_pkey')
    )
    op.create_table('embedding_vector_index_76070006_5206_4e81_876f_151f5d616b3a_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_76070006_5206_4e81_876f_151f5d616b3_pkey')
    )
    op.create_table('embedding_vector_index_f447ed75_3787_499a_9f68_6e42d775acfb_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_f447ed75_3787_499a_9f68_6e42d775acf_pkey')
    )
    op.create_table('embedding_vector_index_31fdeac1_9005_4a2f_9237_e70f4ab65abe_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_31fdeac1_9005_4a2f_9237_e70f4ab65ab_pkey')
    )
    op.create_table('embedding_vector_index_d185d041_439e_4d65_b85c_e90c8ae926fd_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_d185d041_439e_4d65_b85c_e90c8ae926f_pkey')
    )
    op.create_table('embedding_vector_index_e6ae390c_8daf_43fb_9958_3be5bee640d3_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_e6ae390c_8daf_43fb_9958_3be5bee640d_pkey')
    )
    op.create_table('embedding_vector_index_12ff3df9_0e1d_4c87_a37d_5bd2dd63c260_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_12ff3df9_0e1d_4c87_a37d_5bd2dd63c26_pkey')
    )
    op.create_table('embedding_vector_index_e71b2ec6_c516_488e_b665_b1c57ef97c5e_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_e71b2ec6_c516_488e_b665_b1c57ef97c5_pkey')
    )
    op.create_table('embedding_vector_index_3f52b98b_ca31_4000_b796_5ac682bad5da_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_3f52b98b_ca31_4000_b796_5ac682bad5d_pkey')
    )
    op.create_table('embedding_vector_index_7ac532be_f746_4635_a438_82c5d0fe3daa_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_7ac532be_f746_4635_a438_82c5d0fe3da_pkey')
    )
    op.create_table('embedding_vector_index_e4c6a2f6_9403_4ea2_a272_59256809fd72_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_e4c6a2f6_9403_4ea2_a272_59256809fd7_pkey')
    )
    op.create_table('embedding_vector_index_d3e0183e_a108_4599_a7ab_b90e2b7acb95_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_d3e0183e_a108_4599_a7ab_b90e2b7acb9_pkey')
    )
    op.create_table('embedding_vector_index_69950a0f_ffb6_4641_bacf_779929f93f9f_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_69950a0f_ffb6_4641_bacf_779929f93f9_pkey')
    )
    op.create_table('embedding_vector_index_1e3e13c3_2ad7_450b_a7cb_f3ef7efdc569_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_1e3e13c3_2ad7_450b_a7cb_f3ef7efdc56_pkey')
    )
    op.create_table('embedding_vector_index_c24419f0_38cf_45ca_ac5e_81c3c2e787a8_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_c24419f0_38cf_45ca_ac5e_81c3c2e787a_pkey')
    )
    op.create_table('embedding_vector_index_e3d705a5_5cd6_4698_aaa4_585bfcb36460_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_e3d705a5_5cd6_4698_aaa4_585bfcb3646_pkey')
    )
    op.create_table('embedding_vector_index_882713d3_5ded_4547_939a_4233f1af81ae_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_882713d3_5ded_4547_939a_4233f1af81a_pkey')
    )
    op.create_table('embedding_vector_index_44b8bc1c_df5a_47cf_82d3_376addd9db79_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_44b8bc1c_df5a_47cf_82d3_376addd9db7_pkey')
    )
    op.create_table('embedding_vector_index_b961ddf5_4f60_49ff_a827_76e22fb5f97e_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_b961ddf5_4f60_49ff_a827_76e22fb5f97_pkey')
    )
    op.create_table('embedding_vector_index_e16132be_d698_4c92_bb19_17bc49400a23_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_e16132be_d698_4c92_bb19_17bc49400a2_pkey')
    )
    op.drop_table('tool_providers')
    op.drop_table('celery_tasksetmeta')
    op.drop_table('celery_taskmeta')
    # ### end Alembic commands ###
